Remove on purpose test fail. Setup validation for remaining tests. All good. 🥳

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -49,10 +49,12 @@ jobs:
       
       - name: Install coverage package for dart
         run: dart pub global activate coverage
+      
       - name: Install jq for processing json in terminal
         run: |
           sudo apt-get update -y
           sudo apt-get install -y jq
+      
       - name: Run client http e2e tests        
         run: |
           melos run test:client:e2e:http
@@ -60,35 +62,42 @@ jobs:
           if $(echo $test_result | jq '.success') == true; then
             echo "No error found: All tests passed";
           else
+            echo "Some test have failed. Pleas verify the logs"
             exit 1;
           fi
 
-#       - name: Run client grpc e2e tests        
-#         run: |
-#           melos run test:client:e2e:grpc | tee cln_grpc.txt
-#           if grep "Some tests failed." -i cln_grpc.txt -q; then
-#             exit 1;
-#           else
-#             echo "No error found: All tests passed";
-#           fi
+      - name: Run client grpc e2e tests        
+        run: |
+          melos run test:client:e2e:grpc | tee cln_grpc.txt
+          export test_result=$(tail -1 packages/dapr_client/test/reports/tests_client_grpc.json)        
+          if $(echo $test_result | jq '.success') == true; then
+            echo "No error found: All tests passed";
+          else
+            echo "Some test have failed. Pleas verify the logs"
+            exit 1;
+          fi
 
-#       - name: Run server http e2e tests        
-#         run: |
-#           melos run test:server:e2e:http | tee srv_http.txt
-#           if grep "Some tests failed." -i srv_http.txt -q; then
-#             exit 1;
-#           else
-#             echo "No error found: All tests passed";
-#           fi
+      - name: Run server http e2e tests        
+        run: |
+          melos run test:server:e2e:http | tee srv_http.txt
+          export test_result=$(tail -1 packages/dapr_server/test/reports/tests_server_http.json)        
+          if $(echo $test_result | jq '.success') == true; then
+            echo "No error found: All tests passed";
+          else
+            echo "Some test have failed. Pleas verify the logs"
+            exit 1;
+          fi
 
-#       - name: Run server grpc e2e tests        
-#         run: |
-#           melos run test:server:e2e:grpc | tee srv_grpc.txt
-#           if grep "Some tests failed." -i cln_grpc.txt -q; then
-#             exit 1;
-#           else
-#             echo "No error found: All tests passed";
-#           fi
+      - name: Run server grpc e2e tests        
+        run: |
+          melos run test:server:e2e:grpc | tee srv_grpc.txt
+          export test_result=$(tail -1 packages/dapr_server/test/reports/tests_server_grpc.json)        
+          if $(echo $test_result | jq '.success') == true; then
+            echo "No error found: All tests passed";
+          else
+            echo "Some test have failed. Pleas verify the logs"
+            exit 1;
+          fi
       
       - name: Upload coverage to Codecov
         uses: codecov/codecov-action@v2
